import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
globalThis.React = {};
const source = await readFile(new URL('../frontend/permissions.js', import.meta.url), 'utf8');
const {ruleCategory, extensionList, presetRule} = await import(`data:text/javascript;base64,${Buffer.from(source).toString('base64')}`);
const presets = [{id:'video',name:'视频',color:'#7560ad',extensions:['mp4','mkv']}, {id:'text',name:'文本',color:'#278477',extensions:['txt','md']}];
assert.deepEqual(extensionList('.MP4，mkv  mp4, .custommovie'), ['mp4','mkv','custommovie']);
const rule = presetRule(presets[0], 'none');
assert.equal(rule.tier,'none', 'Adding a preset must not automatically grant content access');
rule.extensions = ['custommovie'];
assert.equal(ruleCategory(rule,presets).name, '视频', 'Edited extensions retain the chosen category');
assert.deepEqual(presets[0].extensions, ['mp4','mkv'], 'Preset templates remain reusable');
assert.equal(ruleCategory({extensions:['md']},presets).name,'文本', 'Older rules infer their category');
assert.equal(ruleCategory({extensions:[]},presets).name,'全部格式');
assert.equal(ruleCategory(JSON.parse(JSON.stringify(rule)),presets).color,'#7560ad');
console.log('PASS named presets, editable extensions, stable colors and preserved access tier');
